### ISSUE TITLE
wrong and very large joint position after robot had a collision with objects

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#2436]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2436)) by Anonymous.**

----------------------------------------
Gazebo will keep providing wrong and very large joint position after robot had a collision ( with large contact force) with the ground or some objects in gazebo world. And the `joint_states` will keep the wrong data even if the robot has moved to another pose!

`/joint_states`(joint limit should be (-pi, pi) as defined in URDF):

```
header: 
  seq: 14205682
  stamp: 
    secs: 71085
    nsecs: 101000000
  frame_id: ''
name: ['elbow_joint', 'shoulder_lift_joint', 'shoulder_pan_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
position: [-8.51584976541768, -22393.868370150947, -23210.903847882473, -23059.99195414233, 7.4320796024417355, 9.18637489720941]
velocity: [0.00021875832846863282, 0.00585327683488699, 0.003416905486500389, -0.0001427822974524656, 6.232113829809081e-05, 1.6280227906504893e-06]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
