### ISSUE TITLE
Please help test Flatpak Gazebo build, crashing.

### ISSUE THREAD

**Issue by kevinsmia1939** [osrf/gazebo#2986]
This is after I manage to unbundle FreeImage.
https://github.com/osrf/gazebo/issues/2984

I successfully build Gazebo with github CI.
https://github.com/flathub/flathub/pull/2296

Please try it out.
First, install Flatpak. Setup according to your Linux distro.
https://flatpak.org/setup/

Installing the test build by using this command.
`
flatpak install --user https://dl.flathub.org/build-repo/45107/org.gazebosim.Gazebo.flatpakref`

Note that this is not release to Flathub yet.
This install is 500 MB in size because I did not delete any left over development files from its dependencies yet. I will trim it down when ready to ship.

Gazebo flatpak can be run with.
`flatpak run org.gazebosim.Gazebo`

I have not made desktop file for Gazebo yet, this is the way to run it at the moment.

Pass verbose option to Gazebo with something like this.
`flatpak run org.gazebosim.Gazebo --verbose`

Or instead, pass verbose option to Flatpak like this.
`flatpak run -vvv org.gazebosim.Gazebo`

Or access bash in Flatpak like this. And can run Gazebo by typing gazebo in command line inside flatpak.
`flatpak run --command=bash org.gazebosim.Gazebo`

I have issue Gazebo crash on start up. I would like for someone to help test it out.
Thanks.

**Comment by kevinsmia1939** [comment]
Update:
So Gazebo show splash screen and interface, but freeze immediately after that.

`flatpak run org.gazebosim.Gazebo --verbose`
Give me this.
Maybe issue with Orge build in Flatpak manifest.

```
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.122.80
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.122.80
[Msg] Loading world file [/app/share/gazebo-11/worlds/empty.world]

(process:5): Gtk-WARNING **: 04:50:48.219: Locale not supported by C library.
	Using the fallback 'C' locale.
[Wrn] [GuiIface.cc:120] Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
[Wrn] [GuiIface.cc:120] Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

[Err] [main.cc:37] Ogre Error:RuntimeAssertionException: Ogre/ShadowExtrudePointLight not found. Verify that you referenced the 'ShadowVolume' folder in your resources.cfg in initialise at /run/build/ORGE/OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp (line 70)
```
Could this error be relate to this? Only vcpkg version of ORGE work?
https://github.com/osrf/gazebo/issues/2700

ORGE was build like this in Flatpak manifest.

```
  - name: ORGE
    buildsystem: cmake
    config-opts:
      - -DOGRE_INSTALL_DOCS:BOOL=OFF
      - -DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI:BOOL=OFF
      - -DOGRE_BUILD_SAMPLES:BOOL=OFF
      - -DOGRE_BUILD_TESTS:BOOL=OFF
    sources:
      - type: archive
        url: https://github.com/OGRECave/ogre/archive/v1.12.12.zip
        sha256: 87cef6258d65bb03207e150fcd89b9b94ef94609ef657c29ef4991d0777de741
```
